# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            javierquerol.es
tagline:          iOS Development
url:              http://javierquerol.es
paginate:         1
baseurl:          http://JavierQuerol.github.io/poole/
author:
  name:           Javier Querol
  url:            https://twitter.com/javierquerol
  email:          querol.javi@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
